// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCImC3QccEvwMiYUdzsm4KGO9X8HzCrMsg',
    appId: '1:854071685305:web:1ef92eeaa9e1564c2bab68',
    messagingSenderId: '854071685305',
    projectId: 'generation-671ae',
    authDomain: 'generation-671ae.firebaseapp.com',
    storageBucket: 'generation-671ae.firebasestorage.app',
    measurementId: 'G-W73C4E72Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQ1FKa0V3pHMsqrBy-FdPEtD-3HTyF40',
    appId: '1:854071685305:android:aaa76d50e7686bc02bab68',
    messagingSenderId: '854071685305',
    projectId: 'generation-671ae',
    storageBucket: 'generation-671ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6uou8xNux4PI0iDMEPBxJHp81tLQbCmo',
    appId: '1:854071685305:ios:7f06fa4c74debee72bab68',
    messagingSenderId: '854071685305',
    projectId: 'generation-671ae',
    storageBucket: 'generation-671ae.firebasestorage.app',
    iosBundleId: 'com.example.comsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6uou8xNux4PI0iDMEPBxJHp81tLQbCmo',
    appId: '1:854071685305:ios:7f06fa4c74debee72bab68',
    messagingSenderId: '854071685305',
    projectId: 'generation-671ae',
    storageBucket: 'generation-671ae.firebasestorage.app',
    iosBundleId: 'com.example.comsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCImC3QccEvwMiYUdzsm4KGO9X8HzCrMsg',
    appId: '1:854071685305:web:44050c394c5136562bab68',
    messagingSenderId: '854071685305',
    projectId: 'generation-671ae',
    authDomain: 'generation-671ae.firebaseapp.com',
    storageBucket: 'generation-671ae.firebasestorage.app',
    measurementId: 'G-H0HFG15PKD',
  );
}
